name: Publish package

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    publish-package:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - run: yarn install
            - run: yarn run build
            - run: node utils/change-registry.js --registry https://npm.pkg.github.com/
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.MY_PUBISH_PACKAGE_TOKEN}}
            - run: node utils/change-registry.js --registry https://registry.npmjs.org
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.MY_PUBISH_PACKAGE_TOKEN_NPM}}
